### ISSUE TITLE
Dice entropy bias

### ISSUE THREAD

**Issue by limpbrains** [CoboVault/cobo-vault-cold#165]
Hi

I know that you guys using the same method to get binary entropy from dice rolls as https://github.com/iancoleman/bip39

Recently, a serious flaw [was found](https://github.com/iancoleman/bip39/issues/435) in this approach. I think you should also revise the entropy generation algorithm.

**Comment by zhangjun725** [comment]
thanks for your feedback @limpbrains , I have gone through the [issue](https://github.com/iancoleman/bip39/issues/435) and the [pr](https://github.com/iancoleman/bip39/commit/bf96267f89d18f278e78cf02c97ab1e7513fb871), the bias only under  "Use Raw Entropy (3 words per 32 bits)" mode，and the PR seems only affect this mode.
Cobo Vault only support the "24 Words" mode, require users to roll the dice **at least 50 times**, then hash the rolls to get a 256bits entropy. I think the current generation algorithm is ok.

**Comment by jpph** [comment]
@zhangjun725   I think it is better to stick to Ian Coleman implementation. This is the only way to do a trustless implementation on the cobo vault. User can do a test-run with dice roll on Ian Coleman's webpages and your cobo to see that generated adress/xpub are the same. One done, they can do a real dice roll only on the cobo vault.

**Comment by aaronisme** [comment]
> @zhangjun725 I think it is better to stick to Ian Coleman implementation. This is the only way to do a trustless implementation on the cobo vault. User can do a test-run with dice roll on Ian Coleman's webpages and your cobo to see that generated adress/xpub are the same. One done, they can do a real dice roll only on the cobo vault.

@jpph Thanks for your comments, currently our implementation is a subset of Ian Coleman implementation, if user choose 24 Words and Dice in Ian Coleman, he will get the same result  on Cobo Vault.  so we are do stick to lan coleman implemation now ;)

**Comment by jpph** [comment]
Sure for now it is still working but Ian Coleman soon will put live the modification he has done and it will be different...

**Comment by aaronisme** [comment]
> Sure for now it is still working but Ian Coleman soon will put live the modification he has done and it will be different...

Thanks for the info, we will keep an eye on that

**Comment by jpph** [comment]
Hi, Ian Coleman's page ha sheen updated to version 0.5.0. So now the dice roll doesn't produce the same mnemonics as yours.
Regards

**Comment by aaronisme** [comment]
@jpph Thanks for the update, we will check it out

**Comment by aaronisme** [comment]
@jpph our dice implementation is using these options for dice, we have tested seems the result is same. 
![293071605596489_ pic_hd](https://user-images.githubusercontent.com/7855886/99357014-25ff2780-28e6-11eb-9acc-b779b3690a53.jpg)

**Comment by jpph** [comment]
hi, I tested myself also 0.4.3 and 0.5.0 version of ian coleman's page, it produces different raw binary entropy but same bip39 phrase. I think there is a bug somewhere, I have opened an issue on ian coleman github page https://github.com/iancoleman/bip39/issues/457

**Comment by jpph** [comment]
ok, you can check the answer from Ian, modification has been done only when user ask for "raw entropy". When generating for 24 words, the dice roll is put trough a hash function to generate all 256bits needed, even if dice roll count is low.
So, for the 24 word bip39 mnemonic + dice roll, the process remain the same, and no change needed for cobo vault, it still can be verified using the same 24 word option ( which work the same on 0.4.3 and 0.5.0 version).

**Comment by aaronisme** [comment]
@jpph never mind, Thanks for the feedback. I will close this issue now, if there are other changes, please create a new issue.
