### ISSUE TITLE
Flare QR paste verification

### ISSUE THREAD

**Issue by xrpmaxi** [CoboVault/cobo-vault-cold#236]
Hello friends, while I am sure that Cobo and everyone involved has this right it is concerning to me that 
when qr pasting Flare memo ID into ToolKit from Cobo, it is a different string than if I used the Eth address on device and pasted into the commonly used flare memo tool.
Would like to verify that they are same essentially.
Also that that key translates back into my Eth address on wallet without trusting blindly.
Thanks!

**Comment by RareData** [comment]
The message key Cobo Vault provides comes from a dedicated Flare address, derived using the [recommended BIP path](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) _44'/554'/0'/0/0_ for the coming Flare Network. 

This eliminates the risk of users setting an active Ethereum address as message key and provides better cross-chain privacy.
