### ISSUE TITLE
App, when binding, How to Update = broken

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#256]
When binding a Vault with an older version there's a popup with two button, the 2nd one is "How to upgrade"

The words are off so that part of it is off the button and taping the button doesn't do anything.

**Comment by Transisto** [comment]
![image](https://user-images.githubusercontent.com/388716/102705200-c1234e00-4252-11eb-8511-a5dc775ec7c9.png)

**Comment by aaronisme** [comment]
Thanks for the feedback, we check it, which app version are you using and what system is your phone? IOS or Android?

**Comment by caixiao-QA** [comment]
Thanks for the feedback, We have confirmed that this is a bug. This week we will release a new version to fix this problem. Now, you can view the upgrade tutorial through this link. https://support.cobo.com/hc/en-us/articles/360046064053-Upgrading-Firmware.

Sorry for the inconvenience.
