### ISSUE TITLE
Multi-coin firmware export Bitcoin XPUB

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#257]
I think this is a very basic and essential feature and should be on both firmware.

**Comment by aaronisme** [comment]
our current multi-coin firmware is designed for entry-level users who can easily manage their crypto assets, XPub probably is too technical for them. so we do not provide this function on our multi-coin firmware. and for the high-level user, I think the btc-only firmware is a much suitable choice
