### ISSUE TITLE
Detail of signed bitcoin transaction QR is not displayed on the app before broadcast.

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#263]
It's also nor a format compatible with anything else that could parse it in a human readable format.

There is no possible verification of what data is coming out of the vault QR code. IMO this is worst than a having it communicate over bluetooth or USB.

**Comment by aaronisme** [comment]
I think you are using out the companion app?  I think we should provide some tool to help to decode the QR code.  it just using our encoding method(https://github.com/CoboVault/crypto-coin-message-protocol) to encode data into the QR codes.(using bc-ur) and if you are using our btc-only firmware. the signed data are just psbt, you can use other library or tool to do the verification.
