### ISSUE TITLE
Can't update to BTC-ONLY firmware.

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#264]
Starting from multi-coin 2.1.5

I tried latest BTC-ONLY

Wiped device, 

Tried the V1.2.1.BTC-Only

The Vault doesn't seems to be responding at all to what I put on the SD card.

There should be a button within the update section of the app to force read the SD card for firmware and give a feedback.

**Comment by aaronisme** [comment]
you are on the latest muli-coin 2.1.5 firmware. so you can't upgrade to the old version btc-only firmware. you will release a new btc-only firmware in the following days.

**Comment by aaronisme** [comment]
for your feedback, we will put it into our pools. thanks

**Comment by aaronisme** [comment]
please check out our download for the latest btc-only firmware https://cobo.com/hardware-wallet/downloads

**Comment by aaronisme** [comment]
> please check out our download for the latest btc-only firmware https://cobo.com/hardware-wallet/downloads @Transisto
