### ISSUE TITLE
Specter compatibility problem

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#269]
Using BTC-ONLY firmware, I can't scan either the "Device PSBT" or "Standard PSBT"

On Vault I get this
`Scan failed,  Invalid QR code, Check and retry`

**Comment by caixiao-QA** [comment]
Thanks for the feedback,Please check your current Watch-only Wallet mode. If you want to sign specter transactions, please set Watch-only Wallet to Generic Wallet.

![image](https://user-images.githubusercontent.com/37337093/102954467-7897b900-450e-11eb-9816-5545e1546d9a.png)

**Comment by Transisto** [comment]
Thanks
