### ISSUE TITLE
Some wallet not offered address type option. (BlueWallet, BTCPay)

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#272]
When selecting Blue or BTCPAY the option to use Nested Segwit is not offered while both wallet supports it.

**Comment by Transisto** [comment]
https://github.com/CoboVault/cobo-vault-cold/issues/270

**Comment by aaronisme** [comment]
for BlueWallet and BTCPay we are stick to its default address type Native Segwit

**Comment by aaronisme** [comment]
log this as a feature request on our backlog, close this issue now
