### ISSUE TITLE
Scanning an electrum QR code when Vault is set to "Cobo vault" watch wallet crash the device.

### ISSUE THREAD

**Issue by Transisto** [CoboVault/cobo-vault-cold#273]
End up on a forever spin load screen and need to be rebooted.

**Comment by caixiao-QA** [comment]
Thanks for the feedback, we will check it, which cobo vault version are you using ？Which QR code on electrum are you scanning？ if possible, please provide it to us.

**Comment by aaronisme** [comment]
close this issue since no detail feedback

**Comment by Transisto** [comment]
Was scanning a "PSBT" using latest vault, btc only version.

Will try again with the very last version.
