### ISSUE TITLE
Seed Verification should be added to Wallet Settings Menu

### ISSUE THREAD

**Issue by 3rdIteration** [CoboVault/cobo-vault-cold#47]
It is currently possible to do a "dry-run recovery" style of workflow on the Cobo Vault via the "forgot password" button when unlocking the device. Ideally this is something that should also be accessible for users via the system menu. (Just for the situation where a user may have lost track of which seed is currently initialised in the Vault)

**Comment by aaronisme** [comment]
Interesting point, but I think an master key fingerprint can resolve this  issue (for identifying the seed) ?

**Comment by 3rdIteration** [comment]
A master key is useful for experienced users, but most users don't have a secure way to go from seed -> master key fingerprint if they only own one hardware wallet and have multiple seeds. (For whatever reason) 


The typical situation that leads to this issue is that a user will re-key their device with a new seed, or perhaps have multiple devices, and simply assume that they will remember which is which. (And then forget)

If you have any Trezor, Ledger, Keepkey or Coldcard devices handy, you can have a look at how they implement this functionality in their various platforms.

**Comment by aaronisme** [comment]
interesting point, we will consider that and thanks for the feedback

**Comment by 3rdIteration** [comment]
@aaronisme looks like this has been added in 1.4 now, can probably close this one?

**Comment by aaronisme** [comment]
yes
