### ISSUE TITLE
Cobo Vault (And companion app) generate "Bitcoin Style" p2sh addresses only for Litecoin

### ISSUE THREAD

**Issue by 3rdIteration** [CoboVault/cobo-vault-cold#48]
As it stands, the device generates Litecoin addresses that start with a "3", not an "M". While these are technically valid, some LTC wallets no longer support accepting these addresses to send Litcoin. (As a way to prevent users from sending Litcoin to a Bitcoin Address) If the user is in such a situation, they will need to use an address converter before they are able to send funds to the Cobo Vault.

**Comment by aaronisme** [comment]
resolved on latest multi-coin firmware
