### ISSUE TITLE
Cobo Partner App: Transaction view doesn't respect currency settings

### ISSUE THREAD

**Issue by 3rdIteration** [CoboVault/cobo-vault-cold#51]
Not sure exactly which repo is the right one for the Android/iOS app.... But anyway...

Basically the transaction view will always use the default RMB currency, regardless of which currency has been selected in-app. The total value for each coin will be correctly displayed in the selected currency, just not transaction details.

**Comment by aaronisme** [comment]
currently, the partner app is not open source. I have a plan to opensource it. and I think that probably a bug is our system will figure it out, and Thanks for the feedback

**Comment by aaronisme** [comment]
in the latest  companion  app, this issue has been fixed
