### ISSUE TITLE
Cobo Partner App: Historical transactions (created prior to the wallet being imported into the app) have incorrect timestamp and ordering

### ISSUE THREAD

**Issue by 3rdIteration** [CoboVault/cobo-vault-cold#52]
As part of my testing for the device, I imported a few seeds which already had a number of transactions associated with them. What I observed was that all of these transactions were listed in the Cobo app as having occured at the time that I imported the seed, as opposed to when they occured onchain. (sometimes months earlier) 

To confuse things more, this also resulted in these transactions being presented in a random order.

**Comment by aaronisme** [comment]
Thanks for the feedback, that is a bug in our system. after importing the seed, our system will fetch some historical transaction data on the blockchain which aims to provide a better user experience. but the timestamps are not processing correctly

**Comment by aaronisme** [comment]
this issue has been fixed
