### ISSUE TITLE
Bitcoin-Only Feature Request: Ability to add multiple accounts

### ISSUE THREAD

**Issue by 3rdIteration** [CoboVault/cobo-vault-cold#53]
I understand why this is an issue in terms of being newbie friendly, but it would be great if this were possible on the device for BTC-Only firmware, even if not supported in the Cobo app. (eg: required Electrum, Bluewallet, Wasabi to use)

**Comment by aaronisme** [comment]
I think in our latest release, electrum, BlueWallet and Wasabi are all supported but we will wait for there next release, PR have been merged.

**Comment by aaronisme** [comment]
all these apps have been supported
